version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
  pghttpasync:
    build: .
    image: pghttpasync
    environment:
      PGHOST: "db"
      PGUSER: "postgres"
      LOGLEVEL: "DEBUG"
